services:
  api:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.multi
    #   target: api-build
    image: ghcr.io/edo-andres/librechat-avi-api:latest
    #container_name: LibreChat-API
    expose:
      - 3080
    depends_on:
      - mongodb
      - rag_api
    restart: always
    networks:
      - dokploy-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ../files/.env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
      #- ELEVENLABS_AGENT_ID=${ELEVENLABS_AGENT_ID}
    volumes:
      - ../files/librechat.yaml:/app/librechat.yaml     
      - ../files/images:/app/client/public/images
      - ../files/uploads:/app/uploads
      - ../files/logs:/app/api/logs

  client:
    image: nginx:1.27.0-alpine
    #container_name: LibreChat-NGINX
    expose:
      - 80
    depends_on:
      - api
    restart: always
    networks:
      - dokploy-network
    # ✅ Dokploy v0.7.0+ maneja Traefik automáticamente
    # ✅ Configura tu dominio desde la UI de Dokploy:
    #    - Host: avi.granade.io
    #    - Path: /
    #    - Container Port: 80
    #    - HTTPS: ON
    #    - Certificate: letsencrypt
    # ❌ YA NO se necesitan etiquetas manuales de Traefik
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf

  mongodb:
    #container_name: chat-mongodb
    # ports:  # Uncomment this to access mongodb from outside docker, not safe in deployment
    #   - 27018:27017
    image: mongo
    restart: always
    networks:
      - dokploy-network
    volumes:
      - ../files/data-node:/data/db
    command: mongod --noauth

  meilisearch:
    #container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.12.3
    restart: always
    # ports: # Uncomment this to access meilisearch from outside docker
    #   - 7700:7700 # if exposing these ports, make sure your master key is not the default value
    networks:
      - dokploy-network
    env_file:
      - ../files/.env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ../files/meili_data_v1.12:/meili_data

  vectordb:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    networks:
      - dokploy-network
    volumes:
      - ../files/pgdata2:/var/lib/postgresql/data

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
    restart: always
    networks:
      - dokploy-network
    depends_on:
      - vectordb
    env_file:
      - ../files/.env

volumes:
  pgdata2:

networks:
  dokploy-network:
    external: true
