services:
  api:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.multi
    #   target: api-build
    image: ghcr.io/edo-andres/librechat-avi-api:latest
    #container_name: LibreChat-API
    restart: always
    networks:
      - dokploy-network
    extra_hosts:
    - "host.docker.internal:host-gateway"
    env_file:
      - ../files/.env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
      - ELEVENLABS_AGENT_ID=${ELEVENLABS_AGENT_ID}
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs
    depends_on:
      - mongodb
      - rag_api

  client:
    image: nginx:1.27.0-alpine
    #container_name: LibreChat-NGINX
    restart: always
    ports:
      - 80  # Solo puerto interno - Traefik maneja el externo
    networks:
      - dokploy-network
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    labels:
      # Labels de Traefik para HTTPS automático con Let's Encrypt
      - "traefik.enable=true"
      - "traefik.http.routers.librechat-avi.rule=Host(`avi.granade.io`)"
      - "traefik.http.routers.librechat-avi.entrypoints=websecure"
      - "traefik.http.routers.librechat-avi.tls.certResolver=letsencrypt"
      - "traefik.http.services.librechat-avi.loadbalancer.server.port=80"

  mongodb:
    #container_name: chat-mongodb
    # ports:  # Uncomment this to access mongodb from outside docker, not safe in deployment
    #   - 27018:27017
    image: mongo
    restart: always
    networks:
      - dokploy-network
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth

  meilisearch:
    #container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.12.3
    restart: always
    # ports: # Uncomment this to access meilisearch from outside docker
    #   - 7700:7700 # if exposing these ports, make sure your master key is not the default value
    networks:
      - dokploy-network
    env_file:
      - ../files/.env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./meili_data_v1.12:/meili_data

  vectordb:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    networks:
      - dokploy-network
    volumes:
      - pgdata2:/var/lib/postgresql/data

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
    restart: always
    networks:
      - dokploy-network
    depends_on:
      - vectordb
    env_file:
      - ../files/.env

volumes:
  pgdata2:

networks:
  dokploy-network:
    external: true
